### PR TITLE
Update route.py

### PR DESCRIPTION
**Pull request by ahinojos0029**
list[dict] should have a capital L

### CODE REVIEW

**Comment by jnsougata** [comment]
well ig i din't use typing module. please import List from typing and use it 
i.e. edit your pr

**Comment by ABadGame** [comment]
alright got it

**Comment by ABadGame** [comment]
> well ig i din't use typing module. well please import List from typing and use it i.e. edit your pr

Imported List from typing.

**Comment by jnsougata** [comment]
> > well ig i din't use typing module. well please import List from typing and use it i.e. edit your pr
> 
> Imported List from typing.

heya... after your pull I actually updated all typings. thanks for this pr I will be it closing now

**Pull request closed without merging**
